#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
cd "$(dirname "$0")/.."
if ! brew check-strta-enabled ; then exit 1; fi

PROJ_DIR=$(pwd)
PROJ_NAME=$(basename $PROJ_DIR)

# Bootstrap first
echo "==> Execute ./script/bootstrap"
path="$(dirname "$0")/bootstrap"
$path
echo "==> Bootstrap complete"

# Setup the database
bin/rake db:create
bin/rake db:reset

# Install or update Foreman
if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  echo "==> Installing or updating Foreman gem…"
  gem install foreman
  true
fi

# Ensure DNS and setup nginx
brew setup-ssl $PROJ_NAME "${PROJ_DIR}/config/dev/ssl"
brew setup-nginx-conf $PROJ_NAME $PROJ_DIR config/dev/nginx.conf.erb \
    --extra-val=socket_dir=$PROJ_DIR/tmp/sockets \
    --extra-val=log_dir=$PROJ_DIR/log
exit

